AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - lib/one_gadget/builds/*.rb

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Rails:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 120

Style/FileName:
  Enabled: false
